version: '2'
services:
  mooc-mysql:
    extends:
      file: mysql.yml
      service: mooc-mysql
    networks:
      mooc-net:
        aliases:
          - MASTER_DB_SERVER
          - SLAVE_DB_SERVER_1
          - SLAVE_DB_SERVER_2
  mooc-redis:
    extends:
      file: redis.yml
      service: mooc-redis
    networks:
      mooc-net:
        aliases:
          - REDIS_SERVER
  mooc-monitor:
    extends:
      file: monitor.yml
      service: mooc-monitor
    networks:
      mooc-net:
        aliases:
          - MONITOR_SERVER
networks:
    mooc-net:
      name: mooc-net