version: '2'
services:
  mooc-redis:
    image: bitnami/redis:4.0
    environment:
      #            - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    #        volumes:
    #            - ./data/redis/data:/bitnami
    ports:
      - 6379:6379